name: 'Store GitHub Run ID in PostgreSQL'
description: 'Fetches the value of GitHub environment variable GITHUB_RUN_ID and stores it into a PostgreSQL database.'
author: 'demakks'

# Define your inputs here.
inputs:
  githubrunid:
    description: 'this is runid of a build'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
