name: 'buildrun_action'
description: 'Stores the run ids to the database'
author: 'demakks'

# Define your inputs here.
inputs:
  githubrunid:
    description: 'this is runid of a build'
    required: true
   

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
