name: Store GitHub Run ID

on:
  push:
    branches:
      - main

jobs:
  store-github-run-id:
    runs-on: ubuntu-latest
    steps:
      - name: Store GitHub Run ID in PostgreSQL
        uses: demakks/buildrun_action@v1
